### ISSUE TITLE
INVALID_LED_DETAILS, Must specify both ledOnMs and ledOffMs to configure the blink cycle on older versions of Android before Oreo

### ISSUE THREAD

**Issue by Junama** [mu-dawood/fcm_config#26]

**Comment by tebalink** [comment]
] Unhandled Exception: PlatformException(invalid_led_details, Must specify both ledOnMs and ledOffMs to configure the blink cycle on older versions of Android before Oreo, null, null)
E/flutter (11829): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
E/flutter (11829): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter (11829): <asynchronous suspension>
E/flutter (11829): #2      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:234)
E/flutter (11829): <asynchronous suspension>
E/flutter (11829): #3      NotificationManager.displayNotificationFrom (package:fcm_config/src/io_notifications_manager.dart:356)
E/flutter (11829): <asynchronous suspension>
E/flutter (11829): 




[✓] Flutter (Channel stable, 3.0.0, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en-EG)
    • Flutter version 3.0.0 at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/tebalink/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] Connected device (4 available)
    • SM G610F (mobile) • 5203fd5afa51b33f          • android-arm   • Android 8.1.0 (API 27)
    • SM T295 (mobile)  • R9WR603YMCJ               • android-arm64 • Android 11 (API 30)
    • sayed (mobile)    • 00008101-000251C60C01001E • ios           • iOS 16.0 20A362
    • macOS (desktop)   • macos                     • darwin-arm64  • macOS 12.6 21G115 darwin-arm (Rosetta)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0
